<#
MIT License
Copyright (c) 2026 1abcdefggs (https://github.com/1abcdefggs/google-cloud-agent-platform)

.SYNOPSIS
Quickstart setup script for Google Cloud Agent Platform (Gemini API)

To use this, you must first configure it for use with a project in Google Cloud.

This patch connects to Google Cloud-based agents (such as Gemini) from the IDE to test basic chat functionality. 
I established the connection using the standard method and subsequently converted the process into a batch file. 

I have not verified that it actually works.

.DESCRIPTION
This script automates the initial setup for using the Google Cloud Gen AI SDK.
It configures the necessary environment variables, installs/updates the SDK,
generates a sample Python script (request.py) to test the Gemini 3.6 Flash model,
and executes the script to verify the cloud connection.

.LINK
Official Documentation: 
You can connect by following the instructions here.
https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/start

.USAGE INSTRUCTIONS (2 Patterns)
[Pattern 1: Run as a saved file]
1. Save this code as a file named `quicksetup-agent-platform.ps1`.
2. Change "YOUR_PROJECT_ID" in the code below to your actual Google Cloud Project ID.
3. Open your PowerShell terminal, navigate to the folder, and run: 
   .\quicksetup-agent-platform.ps1

[Pattern 2: Copy and paste directly into the terminal]
1. Change "YOUR_PROJECT_ID" in the code below to your actual Google Cloud Project ID.
2. Copy the entire code and paste it directly into your PowerShell terminal.
3. Press Enter to execute. 
   (Note: The setup script itself will not be saved, but request.py will be generated).

.PREREQUISITES
- Python and pip must be installed on your system.
- Google Cloud CLI (gcloud) must be authenticated. 
  (Run `gcloud auth application-default login` before running this script).
- A valid Google Cloud Project with the Agent Platform API enabled.
#>

# 1. Set necessary environment variables
Write-Host "=== 1. Setting environment variables... ===" -ForegroundColor Cyan

# [!] Replace "YOUR_PROJECT_ID" with your actual Google Cloud Project ID.
# Note: This is your unique Project ID (e.g., "my-project-123"), not the Project Name.
$env:GOOGLE_CLOUD_PROJECT = "YOUR_PROJECT_ID"

# [!] Specify the region for the API request.
# "global" routes automatically to the optimal location.
# Other examples: "us-central1" (Iowa, USA) or "asia-northeast1" (Tokyo, Japan).
$env:GOOGLE_CLOUD_LOCATION = "us-central1"

# [!] Set to "True" to route requests to the enterprise-grade Vertex AI (Agent Platform) backend.
$env:GOOGLE_GENAI_USE_ENTERPRISE = "True"

# 2. Install / Update Python SDK
Write-Host "=== 2. Installing Google Gen AI SDK... ===" -ForegroundColor Cyan
pip install --upgrade google-genai

# 3. Automatically create a test script (request.py)
Write-Host "=== 3. Creating request.py... ===" -ForegroundColor Cyan
$pythonCode = @"
from google import genai
from google.genai.types import HttpOptions
import os

# Initialize the Gemini client.
# Note: This automatically reads the GOOGLE_CLOUD_PROJECT, GOOGLE_CLOUD_LOCATION, 
# and GOOGLE_GENAI_USE_ENTERPRISE environment variables set in Step 1.
client = genai.Client(
    project=os.environ.get("GOOGLE_CLOUD_PROJECT"),
    location=os.environ.get("GOOGLE_CLOUD_LOCATION"),
    http_options=HttpOptions(api_version="v1")
)

# Send a prompt request to the Google Cloud Agent Platform.
response = client.models.generate_content(
    # Specify the model. 
    # Available Serverless Google Models on Agent Platform:
    # - "gemini-3.7-flash"
    # - "gemini-3.6-flash"      (NEW: Latest GA model, near-Pro performance)
    # - "gemini-3.5-flash-lite" (NEW: Ultra-fast & cost-effective lightweight model)
    # - "gemini-3.5-flash"      (Standard Flash model)
    model="gemini-3.7-flash",
    
    # The actual text prompt (question) you want to ask the AI.
    
    contents="Hello, how are you?",
)

print("--- Response from Cloud ---")
# Display the response from the AI.
print(response.text)
print("--------------------------")
"@

Set-Content -Path "request.py" -Value $pythonCode -Encoding UTF8

# 4. Execute the test script
Write-Host "=== 4. Executing the test script... ===" -ForegroundColor Cyan

# Run the dynamically generated Python script.
# If the setup is correct, you should see a text response generated by the Gemini model.
# Note: If you encounter a Permission or Authentication error here, please verify:
# 1. You have run `gcloud auth application-default login`
# 2. The provided YOUR_PROJECT_ID is completely correct.
python request.py

Write-Host "=== All setup and testing completed successfully! ===" -ForegroundColor Green
